apiVersion: v1
kind: Service
metadata:
  name: wiz-{{ .Values.global.environment }}-app-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: wiz-{{ .Values.global.environment }}-app