apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiz-app-dev
  # This metadata namespace is WHERE ARGOCD LIVES. 
  # ArgoCD only looks for Application CRDs in its own namespace.
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: 'https://github.com/grahamschuckman/wiz-techtask-manifests.git'
    targetRevision: HEAD
    path: wiz-app-chart
    helm:
      values: |
        global:
          environment: dev
  
  destination:
    # 1. Points to the local EKS cluster ArgoCD lives on
    server: 'https://kubernetes.default.svc'
    # 2. Points to your intended application home
    namespace: wiz-dev-app 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # This syncOption ensures ArgoCD allows the Helm chart to create 
    # the namespace if it doesn't exist yet.
    syncOptions:
      - CreateNamespace=true